Fix not overwriting all existing assets
drone-plugins/drone-github-release pull request #109
Opened 2022-04-18 16:13 UTC by brooksn

This PR fixes an issue where overwriting some assets in releases with more than 30 assets can fail with a 422 error from GitHub (possibly related to #88).

2022-04-18 16:17 UTC, nikolaishields approved these changes

2022-04-18 20:06 UTC, donny-dont requested changes
Similar functionality is in `drone-github-release-download` at https://github.com/drone-plugins/drone-github-release-download/blob/master/plugin/impl.go#L211-L263 so that makes me think that this code can be simplified.

Also see https://github.com/google/go-github/blob/04b8ae92eb0e72d3fd220a5e479dfc5b82048508/github/examples_test.go#L154-L172 which also reuses a `&github.ListOptions{}`

2022-04-18 20:06 UTC, donny-dont commented on plugin/release.go
> +	var listOpts *github.ListOptions
```suggestion
	listOpts := &github.ListOptions{PerPage: 10}
```

2022-04-18 20:06 UTC, donny-dont commented on plugin/release.go
> +		}
```suggestion
```

2022-04-19 15:11 UTC, brooksn commented
> Similar functionality is in `drone-github-release-download` at https://github.com/drone-plugins/drone-github-release-download/blob/master/plugin/impl.go#L211-L263 so that makes me think that this code can be simplified.

Thank you @donny-dont, I added that change.

2022-04-19 15:12 UTC, donny-dont approved these changes
:shipit:

2022-04-19 15:14 UTC, donny-dont commented
No idea why status isn’t coming back on this cause there was a build at https://cloud.drone.io/drone-plugins/drone-github-release/195 going to merge with admin and look at it later

2022-04-19 15:14 UTC, merged